name: Manual Build and Push

# Run workflow by manual dispatch
on:
  workflow_dispatch:
    inputs:
      cl_branch:
        description: 'If set, the desired branch of control libraries'
        required: false
        default: 'develop'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: Build and publish image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          IMAGE_NAME=network-interfaces:latest
          docker build . \
            --build-arg CONTROL_LIBRARIES_BRANCH=${{ inputs.cl_branch }} \
            --tag ${IMAGE_NAME}
        shell: bash

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        shell: bash

      - name: Push image
        run: |
          IMAGE_NAME=network-interfaces:latest
          docker tag ${IMAGE_NAME} ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
        shell: bash